# Generated by Django 6.1.1 on 2026-09-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(help_text='Latitude in degrees (-90 to 90)')),
                ('longitude', models.FloatField(help_text='Longitude in degrees (-180 to 180)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
